import { GeneratedContent, NewsItem } from "../types";

/**
 * 生成 HTML 邮件模版
 */
const generateEmailHtml = (content: GeneratedContent): string => {
  const renderNewsSection = (title: string, items: NewsItem[], color: string) => `
    <div style="margin-bottom: 30px;">
      <h3 style="color: ${color}; border-bottom: 2px solid ${color}; padding-bottom: 10px; font-family: sans-serif;">${title}</h3>
      ${items.map(item => `
        <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-radius: 8px;">
          <div style="font-size: 16px; font-weight: bold; color: #333; margin-bottom: 5px;">
             <a href="${item.source_url}" style="text-decoration: none; color: #333;">${item.title_cn}</a>
          </div>
          <div style="font-size: 14px; color: #666; margin-bottom: 8px;">${item.title_en}</div>
          <div style="font-size: 14px; color: #444; line-height: 1.6;">${item.summary_cn}</div>
          <div style="margin-top: 8px; text-align: right;">
            <a href="${item.source_url}" style="font-size: 12px; color: ${color}; text-decoration: none; border-bottom: 1px dotted ${color};">🔗 阅读全文 / Read Source</a>
          </div>
        </div>
      `).join('')}
    </div>
  `;

  // Render Medical Viral Titles specifically
  const medicalViralHtml = content.medical_viral_titles && content.medical_viral_titles.length > 0 ? `
    <div style="background: #f6ffed; border: 1px solid #b7eb8f; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
       <div style="color: #52c41a; font-weight: bold; margin-bottom: 10px;">🩺 健康热榜 (Health Trending)</div>
       <ul style="margin: 0; padding-left: 20px; color: #389e0d;">
         ${content.medical_viral_titles.map(t => `<li>${t}</li>`).join('')}
       </ul>
    </div>
  ` : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .date { color: #888; font-size: 14px; }
        .viral-box { background: #fff0f6; border: 1px solid #ffadd2; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #999; }
        a:hover { opacity: 0.8; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1 style="color: #111; margin-bottom: 5px;">Aurora News Insight</h1>
          <div class="date">${content.date} | Daily Briefing</div>
        </div>

        <div class="viral-box">
          <div style="color: #c41d7f; font-weight: bold; margin-bottom: 10px;">🔥 今日热点 (Viral Insights)</div>
          <ul style="margin: 0; padding-left: 20px; color: #c41d7f;">
            ${content.viral_titles.map(t => `<li>${t}</li>`).join('')}
          </ul>
        </div>

        ${renderNewsSection('🌍 全球时政 (Global News)', content.general_news, '#1677ff')}
        
        <h3 style="color: #52c41a; border-bottom: 2px solid #52c41a; padding-bottom: 10px; font-family: sans-serif; margin-bottom: 15px;">🧬 医学前沿 (Medical & Science)</h3>
        ${medicalViralHtml}
        ${content.medical_news.map(item => `
          <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-radius: 8px;">
            <div style="font-size: 16px; font-weight: bold; color: #333; margin-bottom: 5px;">
               <a href="${item.source_url}" style="text-decoration: none; color: #333;">${item.title_cn}</a>
            </div>
            <div style="font-size: 14px; color: #666; margin-bottom: 8px;">${item.title_en}</div>
            <div style="font-size: 14px; color: #444; line-height: 1.6;">${item.summary_cn}</div>
             <div style="margin-top: 8px; text-align: right;">
                <a href="${item.source_url}" style="font-size: 12px; color: #52c41a; text-decoration: none; border-bottom: 1px dotted #52c41a;">🔗 阅读全文 / Read Source</a>
              </div>
          </div>
        `).join('')}

        <div class="footer">
          <p>Generated by Aurora AI • Verified with Google Grounding</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

/**
 * 通过 Vercel 后端接口发送邮件
 */
export const sendEmail = async (
  recipients: string[], 
  content: GeneratedContent | null
): Promise<{ success: boolean; message?: string }> => {
  if (recipients.length === 0) return { success: false, message: "无收件人" };
  if (!content) return { success: false, message: "无内容可发送" };

  const htmlContent = generateEmailHtml(content);

  try {
    console.log("正在请求后端 /api/send-email ...");
    
    // 调用 Vercel Serverless Function
    // 部署后，这个相对路径会自动指向同域名的 API
    const response = await fetch('/api/send-email', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        to: recipients,
        subject: `[Aurora] 每日简报 - ${content.date}`,
        html: htmlContent,
      }),
    });

    if (response.ok) {
      const data = await response.json();
      return { success: true, message: `邮件发送成功!` };
    } else {
      const errorData = await response.json();
      console.error("Backend Error:", errorData);
      return { success: false, message: `发送失败: ${errorData.error || '未知错误'}` };
    }
  } catch (error: any) {
    console.error("Network Error:", error);
    return { success: false, message: `网络错误: ${error.message}` };
  }
};